@url=http://localhost:3000

### Login de Administrador (Obtener JWT)
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "joaquinAdmin",
    "password": "TPfinal1234"
}

###
@adminToken = {{login.response.body.token}}