@url=http://localhost:3000

// 1. LOGIN (EJECUTAR ESTE BLOQUE PRIMERO EN ESTE ARCHIVO)
// El token se guarda en la variable @token para las peticiones de abajo.
### Login de Administrador (Obtener JWT)
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "joaquinAdmin",
    "password": "TPfinal1234"
}

### Definir la variable para este archivo
@token = {{login.response.body.token}}

@rolIdExistente = 1 

### Consultar todos los roles (Auth Requerida)
GET {{url}}/roles
Authorization: Bearer {{token}}

### Crear nuevo rol (Auth y Rol Admin Requerido)
POST {{url}}/roles
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rol": "admin"
}

### Consultar un rol por ID (Auth Requerida)
GET {{url}}/roles/{{rolIdExistente}}
Authorization: Bearer {{token}}

### Modificar rol por ID (PUT - Auth y Rol Admin Requerido)
PUT {{url}}/roles/{{rolIdExistente}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rol": "SuperAdmin"
}

### Eliminar rol por ID (Auth y Rol Admin Requerido)
DELETE {{url}}/roles/4 
Authorization: Bearer {{token}}