@url=http://localhost:3000

@usuarioId = 1
@rolId = 2

### Login de Administrador (Obtener JWT)
# @name login
POST {{url}}/auth/login
Content-Type: application/json
###
@token = {{login.response.body.token}}

### Consultar relación específica (GET: Ruta Normal - NO Auth Requerida)
GET {{url}}/usuarios-roles/usuarios/{{usuarioId}}/roles/{{rolId}}

### Modificar usuarios-roles (PUT - Auth y Rol Admin Requerido)
PUT {{url}}/usuarios-roles/usuarios/{{usuarioId}}/roles/{{rolId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descripcion": "Descripción actualizada por Joaquin Admin",
    "nivel": 10
}